### ISSUE TITLE
Passing the flat option does not work on windows.

### ISSUE THREAD

**Issue by TKMacmillan** [briangonzalez/gulp-file-contents-to-json#8]
Running Windows 10, passing the flat option does not remove the path. On Mac, it does. Perhaps, this is due to Windows using backslashes in its paths.

**Comment by briangonzalez** [comment]
@jacobbroberg – mind taking a look?

**Comment by jacobbroberg** [comment]
@TKMacmillan Are you using version v0.2.0? I'm running on Windows 7 and it works fine with this version.
I attempted to fix Windows paths in #6 (see d295e82d1dd71c983cd051f27d536df9fc6e2d78). Could you verify that you are using this fix before we try looking into if there are any Windows 7 vs Windows 10 difference?

**Comment by TKMacmillan** [comment]
After uninstalling the plugin and installing again, it looks like this is no longer an issue for me. Thanks!
